Build version 1.0.5:1
NebraLtd/maker-starter-app pull request #173
Opened 2022-06-14 11:06 UTC by Andrewsopoku

**Issue**

- Link:
- Summary: Build version increased

**How**

**Screenshots**

**References**

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

2022-06-15 12:50 UTC, marvinmarnold requested changes
Doesn't package.json need to be bumped too?

2022-06-16 03:12 UTC, marvinmarnold commented
@Andrewsopoku ^^

2022-06-16 09:06 UTC, Andrewsopoku commented
@Andrewsopoku added. Forgot to save.

2022-06-16 22:28 UTC, marvinmarnold commented on package.json
> +    "name": "Nebra",
It's distracting when the indentation changes. Hard to make sure only the expected changes are included.

This is a JS package, so I'm inclined to say 2 spaces is more correct.

2022-06-16 22:28 UTC, marvinmarnold reviewed
Just want to address indenting.

2022-06-20 15:11 UTC, marvinmarnold requested changes
Still a typo

2022-06-20 15:11 UTC, marvinmarnold commented on package.json
> -  "version": "1.0.4",
You accidentally omitted the `5`

2022-06-21 10:52 UTC, Andrewsopoku commented
@marvinmarnold Deploying to Testflight but encountered this issue.
![sds](https://user-images.githubusercontent.com/20680743/174782802-c3531dc7-8e91-4332-b4a8-722a1d2935d2.png)

2022-06-21 15:24 UTC, shawaj commented
@marvinmarnold done

2022-06-21 17:13 UTC, marvinmarnold commented
Thanks @shawaj. @Andrewsopoku can you redeploy the newest code for iOS? I'll take care of Android later.

2022-06-22 14:04 UTC, marvinmarnold approved these changes

2022-06-22 14:51 UTC, merged

2022-06-22 20:42 UTC, marvinmarnold commented
@Andrewsopoku in future release PRs, can you add bullet points for the changelog?